---
title: "NMF, 75 topics Results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(ggplot2)
library(stringr)
library(dplyr)
library(latex2exp)
```

```{r}
df <- read_csv("nmf_df.csv")
```

```{r}
# extract words from topic_words column and create actual list rather than a string

topic_wds_10 <- list()
topic_wds_5 <- list()
topic_wds_3 <- list()

for(i in 1:nrow(df))
{
  wds <- df$topic_words[i]
  wds <- str_replace_all(wds, "[[:punct:]]", "")
  wds <-  strsplit(wds, " ")
  
  top5 <- wds[[1]][1:5]
  top5_str <- paste(top5[1], top5[2], top5[3], top5[4], top5[5], sep = ", ")
  topic_wds_5[i] <- top5_str 
  
  top3 <- wds[[1]][1:3]
  top3_str <- paste(top3[1], top3[2], top3[3], sep = ", ")
  topic_wds_3[i] <- top3_str
  
  top10 <- top5 <- wds[[1]][1:10]
  top10_str <- paste(top10[1], top10[2], top10[3], top10[4], top10[5], 
                     top10[6], top10[7], top10[8], top10[9], top10[10], 
                     sep = ", ")
  topic_wds_10[i] <- top10_str 
}

```

```{r}
df$top_10_words <- as.character(topic_wds_10)
df$top_5_words <- as.character(topic_wds_5)
df$top_3_words <- as.character(topic_wds_3)
```


```{r}
plot_df <- df %>% select(top_5_words, percent_docs_containing_topic)
plot_df <- plot_df[order(plot_df$percent_docs_containing_topic, decreasing=FALSE),]
plot_df$top_5_words <- factor(plot_df$top_5_words, levels = unique(plot_df$top_5_words))

```

```{r}
p_df <- head(plot_df,10)
p_df <- rbind(p_df, tail(plot_df,10))
p_df$group <- c(rep("least",10), rep("most", 10))
```

```{r}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
 
```

```{r}
# Lollipop plot - percentage of docs per topic

text_col <- ifelse(p_df$group == "most", "black", "black")

ggplot(data=p_df, aes(x=percent_docs_containing_topic, y=top_5_words)) +
  geom_segment(aes(x=0, y=top_5_words , xend=percent_docs_containing_topic, yend=top_5_words, color=group), size=2) +
  geom_point(aes(color=group), size=4) + #color="blue", size=1, alpha=1) +
  scale_color_manual(values=c("navy", "orange")) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 13, color = text_col), 
        axis.text.x = element_text(size = 13, color = "black"),
        axis.title.x = element_text(size = 13, color = "black"),
        title = element_text(size = 13, color = "black")) +
  theme(legend.position = "none") +
  ggtitle("Most and Least Represented Topics") +
  ylab("") + #("Topic Words") +
  xlab("Percentage of Documents")


# p2 <- ggplot(data=tail(plot_df,10), aes(x=percent_docs_containing_topic, y=top_5_words)) +
#   geom_segment(aes(x=0, y=top_5_words , xend=percent_docs_containing_topic, yend=top_5_words), color="orange", size=2) +
#   geom_point(color = 'orange', size=4) + #color="blue", size=1, alpha=1) 
#   theme_minimal() +
#   theme(axis.text.y = element_text(size = 10)) +
#   ggtitle("Most Represented Topics") +
#   ylab("Topic - Given by Top 5 Words") +
#   xlab("Percentage of Documents Topic Appears In")  
# 
#   plot_grid(p1, p2, ncol = 1, nrow = 2)
  
```
```{r}
#saveRDS(df, "./nmf_results.rds")
```

```{r}
plot_df <- df %>% select(top_5_words, percent_times_max_topic)
plot_df <- plot_df[order(plot_df$percent_times_max_topic, decreasing=FALSE),]
plot_df$top_5_words <- factor(plot_df$top_5_words, levels = unique(plot_df$top_5_words))

p_df <- head(plot_df,10)
p_df <- rbind(p_df, tail(plot_df,10))
p_df$group <- c(rep("least",10), rep("most", 10))
```



```{r}
# Lollipop plot - Discrete Ranking

text_col <- ifelse(p_df$group == "most", "black", "gray")

ggplot(data=p_df, aes(x=percent_times_max_topic, y=top_5_words)) +
  geom_segment(aes(x=0, y=top_5_words , xend=percent_times_max_topic, yend=top_5_words, color=group), size=2) +
  geom_point(aes(color=group), size=4) + #color="blue", size=1, alpha=1) 
  scale_color_manual(values=c("gray", "orange")) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 13, color = text_col), 
        axis.text.x = element_text(size = 13, color = "black"),
        axis.title.x = element_text(size = 13, color = "black"),
        title = element_text(size = 13, color = "black")) +
  theme(legend.position = "none") +
  ggtitle("Most and Least Dominant Topics") +
  ylab("") +
  xlab("Dominant Topic Percentage")
```


```{r}
pal <- c("#232d4b", "#2c4f6b", "#0e879c", "#60999a", "#d1e0bf", "#d9e12b", "#e6ce3a", "#e6a01d", "#e57200", "#fdfdfd")
```

```{r}
plot_nmf <- df %>% select(top_5_words, coherence_mean)
plot_nmf <- plot_nmf[order(plot_nmf$coherence_mean, decreasing=FALSE),]
plot_nmf$top_5_words <- factor(plot_nmf$top_5_words, levels = unique(plot_nmf$top_5_words))

p_df <- head(plot_nmf,10)
p_df <- rbind(p_df, tail(plot_nmf,10))
p_df
```

```{r}
  # p_df%>%
  #       #arrange(desc(coherence_mean)) %>%
  #       #top_n(-10) %>%
  #       ggplot(aes(top_5_words, coherence_mean)) +
  #       geom_col(show.legend = TRUE, fill = pal[3]) +
  #       labs(x = "Topic Words", y = TeX("$C_V$ Topic Coherence"), title = TeX("Most and Least Coherent Topics")) +
  #       coord_flip() +
  #       theme_bw()

ggplot(data=p_df, aes(x=coherence_mean, y=top_5_words)) +
  geom_segment(aes(x=0, y=top_5_words , xend=coherence_mean, yend=top_5_words), color=pal[3], size=2) +
  geom_point(color = pal[3], size=4) + #color="blue", size=1, alpha=1) 
  theme_minimal() +
  theme(axis.text.y = element_text(size = 10)) +
  labs(y = "Topic Words", x = TeX("$C_V$ Topic Coherence"), title = TeX("Most and Least Coherent   Topics"))
```

```{r}
# create data table for dashboard

opt_res <- df %>% 
  select(coherence_mean, percent_docs_containing_topic, percent_times_max_topic, top_10_words) %>%
  transmute(`Coherence` = round(coherence_mean, 2), 
         `Percent Representation` = percent_docs_containing_topic,
         `Percent Dominant Topic` = percent_times_max_topic,
         `Topic Words` = top_10_words
         )
```

```{r}
opt_res$Coherence <- round(opt_res$Coherence, 2)
opt_res$`Percent Representation` <- round(opt_res$`Percent Representation`, 2)
opt_res$`Percent Dominant Topic` <- round(opt_res$`Percent Dominant Topic`, 2)
```

```{r}
saveRDS(opt_res, "~/dspg20RnD/src/r_shiny_app_v2/data/opt_res.rds")
```


